[window]
#dimensions            = { columns = 0, lines = 0 }
#position              = { x = 0, y = 0 }
padding               = { x = 2, y = 2 }
#dynamic_padding       = true
decorations           = "Full"
opacity               = 0.5
blur                  = true
#startup_mode          = "Windowed"
#title                 = "Alacritty"
#dynamic_title         = true
#class                 = { instance = "Alacritty", general = "Alacritty" }
#decorations_theme_variant = "None"
#resize_increments     = false
#option_as_alt         = "None"

[terminal]
shell = "/bin/zsh"

[font]
size = 15
